settings:
  update_interval: 20

exchanges:
  bittrex:
    required:
      enabled: true

notifiers:
    webhook:
        required:
            url: http://192.250.236.75:8080/ta/webhook
        optional:
            username: null
            password: null

indicators:
  momentum:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - momentum
      hot: 0
      cold: 0
      candle_period: 1h
      period_count: 10
  mfi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - mfi
      hot: 0
      cold: 0
      candle_period: 1h
      period_count: 10
  obv:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - obv
      hot: 0
      cold: 0
      candle_period: 1h
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 30
      cold: 70
      candle_period: 1h
      period_count: 14
  stoch_rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - stoch_rsi
      hot: 20
      cold: 80
      candle_period: 1h
      period_count: 14
  macd:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - macd
      hot: 0
      cold: 0
      candle_period: 1h
  ichimoku:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - leading_span_a
        - leading_span_b
      hot: true
      cold: true
      candle_period: 1h

informants:
  vwap:
    - enabled: true
      signal:
        - vwap
      candle_period: 1h
      period_count: 15
  sma:
    - enabled: true
      signal:
        - sma
      candle_period: 1h
      period_count: 15
  ema:
    - enabled: true
      signal:
        - ema
      candle_period: 1h
      period_count: 15
  bollinger_bands:
    - enabled: true
      signal:
        - upperband
        - middleband
        - lowerband
      candle_period: 1h
  ohlcv:
    - enabled: true
      signal:
        - close
      candle_period: 1h
      period_count: 15

crossovers:
  std_crossover:
    - enabled: false
      alert_enabled: true
      alert_frequency: once
      key_indicator: ema
      key_indicator_index: 0
      key_indicator_type: informants
      key_signal: ema
      crossed_indicator: sma
      crossed_indicator_index: 0
      crossed_indicator_type: informants
      crossed_signal: sma
